### ISSUE TITLE
Failed to create the voronoi_planner/VoronoiPlannerROS planner

### ISSUE THREAD

**Issue by 1256239164** [nkuwenjian/voronoi_planner#4]
[FATAL] [1688187393.988006757, 1.481000000]: Failed to create the voronoi_planner/VoronoiPlannerROS planner, are you sure it is properly registered and that the containing library is built? Exception: Failed to load library /home/lzz/catkin_ws/devel/lib//libvoronoi_planner.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/lzz/catkin_ws/devel/lib//libvoronoi_planner.so: undefined symbol: _ZN6google21kLogSiteUninitializedE)
[move_base-12] process has died [pid 7170, exit code 1, cmd /home/lzz/ROS/catkin_ws/devel/lib/move_base/move_base __name:=move_base __log:=/home/lzz/.ros/log/a4109ab0-17cb-11ee-95b3-f4ce231aa9a5/move_base-12.log].

**Comment by nkuwenjian** [comment]
Hi, thanks very much to report the bug. I will find the cause and fix it as soon as possible.

**Comment by nkuwenjian** [comment]
Hi, the bug has been fixed. Thanks again for your kind reminder.
