### ISSUE TITLE
load voronoi layer fail!

### ISSUE THREAD

**Issue by 1508189250** [nkuwenjian/voronoi_planner#5]
[ INFO] [1689583751.442203077, 4348.226000000]: global_costmap: Using plugin "inflation_layer"
[ INFO] [1689583751.446522833, 4348.230000000]: global_costmap: Using plugin "voronoi_layer"
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  According to the loaded plugin descriptions the class costmap_2d::VoronoiLayer with base class type costmap_2d::Layer does not exist. Declared types are  costmap_2d::InflationLayer costmap_2d::ObstacleLayer costmap_2d::StaticLayer costmap_2d::VoxelLayer
*** Aborted at 1689583751 (unix time) try "date -d @1689583751" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e800005064) received by PID 20580 (TID 0x7f0f842daf00) from PID 20580; stack trace: ***
    @     0x7f0f83bcc980 (unknown)
    @     0x7f0f82303e87 gsignal
    @     0x7f0f823057f1 abort
    @     0x7f0f8296b0a9 (unknown)
    @     0x7f0f82976506 (unknown)
    @     0x7f0f82976571 std::terminate()
    @     0x7f0f829767f5 __cxa_throw
    @     0x7f0f81a365cb pluginlib::ClassLoader<>::loadLibraryForClass()
    @     0x7f0f81a3027b pluginlib::ClassLoader<>::createInstance()
    @     0x7f0f81a1c6a4 costmap_2d::Costmap2DROS::Costmap2DROS()
    @     0x7f0f83e52fb9 planner_manager::PlannerManager::PlannerManager()
    @     0x563d957af9e4 main
    @     0x7f0f822e6c87 __libc_start_main
    @     0x563d957afd3a _start
[planner_manager-3] process has died [pid 20580, exit code -6, cmd

**Comment by nkuwenjian** [comment]
Hi, which version of ROS are you using? Before compiling the voronoi_planner package, please make ensure that the package of [voronoi_layer](https://github.com/nkuwenjian/voronoi_layer) has been successfully compiled in your workspace.

**Comment by 1508189250** [comment]
Hello, I used ubuntu18.04 system, according to your prompt, I switched voronoi_layer and voronoi_planner to melodic-devel, but there is a new problem:


[ WARN] [1689646838.126968561, 3.872000000]: global_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1689646838.127138027, 3.872000000]: global_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1689646838.127496893, 3.872000000]: global_costmap: Using plugin "static_layer"
[ INFO] [1689646838.132331511, 3.877000000]: Requesting the map...
[ INFO] [1689646838.335385063, 4.080000000]: Resizing costmap to 1551 X 2416 at 0.035000 m/pix
[ INFO] [1689646838.433382430, 4.178000000]: Received a 1551 X 2416 map at 0.035000 m/pix
[ INFO] [1689646838.435698982, 4.180000000]: global_costmap: Using plugin "obstacle_layer"
[ INFO] [1689646838.439310451, 4.184000000]:&nbsp; &nbsp; &nbsp;Subscribed to Topics: scan dabai_scan
[ INFO] [1689646838.439345520, 4.184000000]: STR:scan
[ INFO] [1689646838.442406356, 4.187000000]: Creating an observation buffer for source scan, topic scan, frame base_scan
[ INFO] [1689646838.444180761, 4.189000000]: STR:dabai_scan
[ INFO] [1689646838.447044543, 4.192000000]: Creating an observation buffer for source dabai_scan, topic dabai_scan, frame camera_link
[ INFO] [1689646838.452034073, 4.197000000]: global_costmap: Using plugin "inflation_layer"
[ INFO] [1689646838.457082585, 4.202000000]: global_costmap: Using plugin "voronoi_layer"
[ INFO] [1689646838.676789623, 4.418000000]: Created global_planner voronoi_planner/VoronoiPlannerROS
[ WARN] [1689646838.679227606, 4.421000000]: local_costmap: Pre-Hydro parameter "static_map" unused since "plugins" is provided
[ WARN] [1689646838.679559586, 4.421000000]: local_costmap: Pre-Hydro parameter "map_type" unused since "plugins" is provided
[ INFO] [1689646838.679896523, 4.421000000]: local_costmap: Using plugin "static_layer"
[ INFO] [1689646838.682512824, 4.424000000]: Requesting the map...
[ INFO] [1689646838.684966541, 4.427000000]: Resizing static layer to 1551 X 2416 at 0.035000 m/pix
[ INFO] [1689646838.781466663, 4.525000000]: Received a 1551 X 2416 map at 0.035000 m/pix
[ INFO] [1689646838.782989292, 4.526000000]: local_costmap: Using plugin "obstacle_layer"
[ INFO] [1689646838.785490825, 4.529000000]:&nbsp; &nbsp; &nbsp;Subscribed to Topics: scan dabai_scan_01
[ INFO] [1689646838.785511879, 4.529000000]: STR:scan
[ INFO] [1689646838.788913634, 4.532000000]: Creating an observation buffer for source scan, topic scan, frame base_scan
[ INFO] [1689646838.789748842, 4.533000000]: STR:dabai_scan_01
[ INFO] [1689646838.792052956, 4.536000000]: Creating an observation buffer for source dabai_scan_01, topic dabai_scan_01, frame&nbsp;
[ INFO] [1689646838.796982229, 4.541000000]: local_costmap: Using plugin "inflation_layer"
[ INFO] [1689646838.812839533, 4.557000000]: Created local_planner dwa_local_planner/DWAPlannerROS
*** Aborted at 1689646838 (unix time) try "date -d @1689646838" if you are using GNU date ***
PC: @&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0x0 (unknown)
*** SIGSEGV ***@***.***) received by PID 20402 (TID 0x7fe860761700) from PID 0; stack trace: ***
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe8918ad980 (unknown)
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe863ddc861 DynamicVoronoi::isOccupied()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe863de1b3c costmap_2d::VoronoiLayer::updateCosts()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88f6fab72 costmap_2d::LayeredCostmap::updateMap()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88f702124 costmap_2d::Costmap2DROS::updateMap()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88f701bc8 costmap_2d::Costmap2DROS::mapUpdateLoop()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88f74560e boost::_mfi::mf1<&gt;::operator()()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88f743f8a boost::_bi::list2<&gt;::operator()<&gt;()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88f742760 boost::_bi::bind_t<&gt;::operator()()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88f73f922 boost::detail::thread_data<&gt;::run()
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe88e4e4bcd (unknown)
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe8918a26db start_thread
&nbsp; &nbsp; @&nbsp; &nbsp; &nbsp;0x7fe8900c761f clone

**Comment by 1508189250** [comment]
thank you,The code is ready to run。
